window.TREATMENT_ADVICE_REVIEW_DATA = {
  "title": "Treatment Advice Review",
  "count": 50,
  "entries": [
    {
      "sample_index": 1,
      "id": "28_opg_detection_00090_133_jpg.rf.e6d339632a6716c98b495b8fc05ee173__qa_05",
      "source_record_id": "28_opg_detection_00090_133_jpg.rf.e6d339632a6716c98b495b8fc05ee173",
      "source_dataset": "28",
      "condition_category": "caries",
      "redrafted": false,
      "image": "assets/images/sample_001.jpg",
      "question": "What is recommended for the visible Caries?",
      "answer": "A restorative assessment is recommended for the visible caries.",
      "original_answer": "A restorative assessment is recommended for the visible caries."
    },
    {
      "sample_index": 2,
      "id": "25_oral_ct_detection_02241_15491-B-01__qa_02",
      "source_record_id": "25_oral_ct_detection_02241_15491-B-01",
      "source_dataset": "25",
      "condition_category": "single_implant",
      "redrafted": true,
      "image": "assets/images/sample_002.jpg",
      "question": "What follow-up or treatment review is suggested by the visible single implants?",
      "answer": "A follow-up review of the visible single implant is suggested, with attention to peri-implant bone support, the implant-abutment or restorative status, and correlation with symptoms or mobility on clinical exam.",
      "original_answer": "A follow-up evaluation of the single implant is recommended to assess its integration and surrounding tissues."
    },
    {
      "sample_index": 3,
      "id": "25_oral_ct_detection_02212_15470-B-02__qa_02",
      "source_record_id": "25_oral_ct_detection_02212_15470-B-02",
      "source_dataset": "25",
      "condition_category": "single_implant",
      "redrafted": true,
      "image": "assets/images/sample_003.jpg",
      "question": "What follow-up evaluation is suggested based on the presence of the single implant?",
      "answer": "A focused follow-up evaluation of the single implant is suggested, including review of surrounding bone levels, implant position, and whether additional localized imaging is needed if stability or loading is uncertain.",
      "original_answer": "A follow-up evaluation for the single implant is recommended for restorative assessment."
    },
    {
      "sample_index": 4,
      "id": "28_opg_detection_00363_252_jpg.rf.beeb1e3c11bb792302a1c431d133e9c3__qa_04",
      "source_record_id": "28_opg_detection_00363_252_jpg.rf.beeb1e3c11bb792302a1c431d133e9c3",
      "source_dataset": "28",
      "condition_category": "caries",
      "redrafted": false,
      "image": "assets/images/sample_004.jpg",
      "question": "What is recommended for the visible Caries?",
      "answer": "A restorative assessment is recommended for the visible caries.",
      "original_answer": "A restorative assessment is recommended for the visible caries."
    },
    {
      "sample_index": 5,
      "id": "28_opg_detection_00110_13_jpg.rf.7fcdec52865b5504a2845064179b56ab__qa_03",
      "source_record_id": "28_opg_detection_00110_13_jpg.rf.7fcdec52865b5504a2845064179b56ab",
      "source_dataset": "28",
      "condition_category": "impacted_teeth",
      "redrafted": true,
      "image": "assets/images/sample_005.jpg",
      "question": "What is recommended for the visible impacted teeth in the lower left and lower right regions?",
      "answer": "For the impacted teeth in the lower left and lower right regions, a targeted oral surgery review is suggested to assess angulation, contact with the adjacent second molars, and proximity to the mandibular canal before deciding on monitoring versus removal.",
      "original_answer": "A follow-up and further dental review are recommended for the impacted teeth in the lower left and lower right regions."
    },
    {
      "sample_index": 6,
      "id": "28_opg_detection_00118_145_jpg.rf.2fb3053e69517b21a5eb156de920cd05__qa_05",
      "source_record_id": "28_opg_detection_00118_145_jpg.rf.2fb3053e69517b21a5eb156de920cd05",
      "source_dataset": "28",
      "condition_category": "impacted_teeth",
      "redrafted": true,
      "image": "assets/images/sample_006.jpg",
      "question": "What is the recommended course of action for the visible Impacted teeth?",
      "answer": "A practical next step is clinical and radiographic review of the impacted teeth, focusing on eruption path, relationship to the adjacent molar, and inferior alveolar canal proximity to guide observation versus extraction planning.",
      "original_answer": "A follow-up evaluation for the impacted tooth is recommended."
    },
    {
      "sample_index": 7,
      "id": "25_oral_ct_detection_02204_15465-B-04__qa_03",
      "source_record_id": "25_oral_ct_detection_02204_15465-B-04",
      "source_dataset": "25",
      "condition_category": "double_implants",
      "redrafted": true,
      "image": "assets/images/sample_007.jpg",
      "question": "What follow-up or treatment review is suggested by the visible double implants?",
      "answer": "A follow-up review of the visible double implants is suggested, checking their alignment, surrounding osseous support, and the restorative plan or current prosthetic interface at both implant sites.",
      "original_answer": "A follow-up evaluation of the double implants in the lower left area is recommended."
    },
    {
      "sample_index": 8,
      "id": "25_oral_ct_detection_02305_15529-B-03__qa_05",
      "source_record_id": "25_oral_ct_detection_02305_15529-B-03",
      "source_dataset": "25",
      "condition_category": "other",
      "redrafted": true,
      "image": "assets/images/sample_008.jpg",
      "question": "What follow-up evaluation might be considered based on the visible findings?",
      "answer": "A reasonable follow-up is a focused review of the visible implant-supported area, with correlation to prosthetic fit, peri-implant bone support, and the condition of the adjacent dentition.",
      "original_answer": "A follow-up evaluation for the implant and surrounding structures may be considered."
    },
    {
      "sample_index": 9,
      "id": "25_oral_ct_detection_02252_15501-B-01__qa_02",
      "source_record_id": "25_oral_ct_detection_02252_15501-B-01",
      "source_dataset": "25",
      "condition_category": "implant_other",
      "redrafted": true,
      "image": "assets/images/sample_009.jpg",
      "question": "Given the presence of implants, what conservative follow-up evaluation might be recommended?",
      "answer": "A conservative follow-up evaluation could include checking peri-implant bone levels at the visible implant sites, confirming prosthetic stability, and comparing with prior images if available to look for interval change.",
      "original_answer": "A conservative follow-up evaluation could include a restorative assessment of the implants."
    },
    {
      "sample_index": 10,
      "id": "28_opg_detection_00220_18_jpg.rf.3c28b05d9677816b7b57731c677cba78__qa_03",
      "source_record_id": "28_opg_detection_00220_18_jpg.rf.3c28b05d9677816b7b57731c677cba78",
      "source_dataset": "28",
      "condition_category": "caries",
      "redrafted": false,
      "image": "assets/images/sample_010.jpg",
      "question": "What is recommended for the visible Caries?",
      "answer": "A restorative assessment is recommended for the visible caries.",
      "original_answer": "A restorative assessment is recommended for the visible caries."
    },
    {
      "sample_index": 11,
      "id": "25_oral_ct_detection_02256_15502-B-03__qa_02",
      "source_record_id": "25_oral_ct_detection_02256_15502-B-03",
      "source_dataset": "25",
      "condition_category": "implant_other",
      "redrafted": true,
      "image": "assets/images/sample_011.jpg",
      "question": "Given the presence of implants, what conservative follow-up evaluation might be suggested?",
      "answer": "A conservative follow-up evaluation is suggested for the visible implants, with attention to implant position within the ridge, surrounding bone support, and any need for site-specific imaging if restoration or integration remains unclear.",
      "original_answer": "A conservative follow-up evaluation could include a restorative assessment of the implants."
    },
    {
      "sample_index": 12,
      "id": "28_opg_detection_00301_230_jpg.rf.9c65d0f6f6c755efdfdf918906fb9eab__qa_04",
      "source_record_id": "28_opg_detection_00301_230_jpg.rf.9c65d0f6f6c755efdfdf918906fb9eab",
      "source_dataset": "28",
      "condition_category": "caries",
      "redrafted": false,
      "image": "assets/images/sample_012.jpg",
      "question": "What is recommended for the visible Caries?",
      "answer": "A restorative assessment is recommended for the visible caries.",
      "original_answer": "A restorative assessment is recommended for the visible caries."
    },
    {
      "sample_index": 13,
      "id": "25_oral_ct_detection_02207_15466-B-01__qa_02",
      "source_record_id": "25_oral_ct_detection_02207_15466-B-01",
      "source_dataset": "25",
      "condition_category": "single_implant",
      "redrafted": true,
      "image": "assets/images/sample_013.jpg",
      "question": "What follow-up or treatment review is suggested by the visible single implants?",
      "answer": "A treatment review of the visible single implant should include peri-implant bone assessment, evaluation of the planned or existing restoration, and clinical correlation for soft-tissue health and stability.",
      "original_answer": "A restorative assessment is suggested for the visible single implant."
    },
    {
      "sample_index": 14,
      "id": "28_opg_detection_00050_118_jpg.rf.ca60f6089d4024fd3e5f7baf5a49dc2a__qa_05",
      "source_record_id": "28_opg_detection_00050_118_jpg.rf.ca60f6089d4024fd3e5f7baf5a49dc2a",
      "source_dataset": "28",
      "condition_category": "caries",
      "redrafted": false,
      "image": "assets/images/sample_014.jpg",
      "question": "What is recommended for the visible Caries?",
      "answer": "A restorative assessment is recommended for the visible caries.",
      "original_answer": "A restorative assessment is recommended for the visible caries."
    },
    {
      "sample_index": 15,
      "id": "25_oral_ct_detection_02223_15477-B-01__qa_02",
      "source_record_id": "25_oral_ct_detection_02223_15477-B-01",
      "source_dataset": "25",
      "condition_category": "single_implant",
      "redrafted": true,
      "image": "assets/images/sample_015.jpg",
      "question": "What follow-up or treatment review is suggested by the visible single implants?",
      "answer": "A follow-up review is suggested for the visible implant site, including assessment of marginal bone support, prosthetic design or load distribution, and comparison with the surrounding dentition before further restorative steps.",
      "original_answer": "A restorative assessment and follow-up evaluation of the implants are suggested."
    },
    {
      "sample_index": 16,
      "id": "28_opg_detection_00256_211_jpg.rf.1209ca43aa9f8c6331b9ecad172f0f5a__qa_05",
      "source_record_id": "28_opg_detection_00256_211_jpg.rf.1209ca43aa9f8c6331b9ecad172f0f5a",
      "source_dataset": "28",
      "condition_category": "caries",
      "redrafted": false,
      "image": "assets/images/sample_016.jpg",
      "question": "What is recommended for the visible Caries?",
      "answer": "A restorative assessment is recommended for the visible caries.",
      "original_answer": "A restorative assessment is recommended for the visible caries."
    },
    {
      "sample_index": 17,
      "id": "28_opg_detection_00259_212_jpg.rf.535c4c8f814276827b7a2b53d64dab44__qa_05",
      "source_record_id": "28_opg_detection_00259_212_jpg.rf.535c4c8f814276827b7a2b53d64dab44",
      "source_dataset": "28",
      "condition_category": "caries",
      "redrafted": false,
      "image": "assets/images/sample_017.jpg",
      "question": "What is recommended for the visible caries in the lower center?",
      "answer": "A restorative assessment is recommended for the visible caries in the lower center.",
      "original_answer": "A restorative assessment is recommended for the visible caries in the lower center."
    },
    {
      "sample_index": 18,
      "id": "28_opg_detection_00129_149_jpg.rf.bb2d08162e889793bd3e92bc74b14c2c__qa_04",
      "source_record_id": "28_opg_detection_00129_149_jpg.rf.bb2d08162e889793bd3e92bc74b14c2c",
      "source_dataset": "28",
      "condition_category": "caries",
      "redrafted": false,
      "image": "assets/images/sample_018.jpg",
      "question": "What is recommended for the visible Caries?",
      "answer": "A restorative assessment is recommended for the visible caries.",
      "original_answer": "A restorative assessment is recommended for the visible caries."
    },
    {
      "sample_index": 19,
      "id": "28_opg_detection_00248_205_jpg.rf.8adb0fdeac4c1297854cce53774dbe99__qa_05",
      "source_record_id": "28_opg_detection_00248_205_jpg.rf.8adb0fdeac4c1297854cce53774dbe99",
      "source_dataset": "28",
      "condition_category": "caries",
      "redrafted": false,
      "image": "assets/images/sample_019.jpg",
      "question": "What is recommended for the visible caries in the center and lower left regions?",
      "answer": "A restorative assessment is recommended for the visible caries in the center and lower left regions.",
      "original_answer": "A restorative assessment is recommended for the visible caries in the center and lower left regions."
    },
    {
      "sample_index": 20,
      "id": "28_opg_detection_00542_94_jpg.rf.b4bdcefa8e6d21867085a9e7db0f2ddd__qa_05",
      "source_record_id": "28_opg_detection_00542_94_jpg.rf.b4bdcefa8e6d21867085a9e7db0f2ddd",
      "source_dataset": "28",
      "condition_category": "caries",
      "redrafted": false,
      "image": "assets/images/sample_020.jpg",
      "question": "What is recommended for the visible Caries?",
      "answer": "A restorative assessment is recommended for the visible caries.",
      "original_answer": "A restorative assessment is recommended for the visible caries."
    },
    {
      "sample_index": 21,
      "id": "25_oral_ct_detection_02149_15428-B-01__qa_02",
      "source_record_id": "25_oral_ct_detection_02149_15428-B-01",
      "source_dataset": "25",
      "condition_category": "other",
      "redrafted": true,
      "image": "assets/images/sample_021.jpg",
      "question": "What next-step treatment consideration is suggested by the visible findings?",
      "answer": "A reasonable next step is a focused implant-site review, with clinical correlation and targeted imaging if needed to confirm the position of the visible implant and its relationship to adjacent teeth and surrounding bone.",
      "original_answer": "A restorative assessment is suggested to evaluate the condition of the implants and surrounding structures."
    },
    {
      "sample_index": 22,
      "id": "28_opg_detection_00298_22_jpg.rf.46d7281e0c2dca48c512e430039341d8__qa_05",
      "source_record_id": "28_opg_detection_00298_22_jpg.rf.46d7281e0c2dca48c512e430039341d8",
      "source_dataset": "28",
      "condition_category": "caries",
      "redrafted": false,
      "image": "assets/images/sample_022.jpg",
      "question": "What is recommended for the visible Caries?",
      "answer": "A restorative assessment is recommended for the visible caries.",
      "original_answer": "A restorative assessment is recommended for the visible caries."
    },
    {
      "sample_index": 23,
      "id": "25_oral_ct_detection_02260_15502-B-07__qa_03",
      "source_record_id": "25_oral_ct_detection_02260_15502-B-07",
      "source_dataset": "25",
      "condition_category": "single_implant",
      "redrafted": true,
      "image": "assets/images/sample_023.jpg",
      "question": "What follow-up or treatment review is suggested by the visible single implants?",
      "answer": "A follow-up review of the visible implant area is suggested, paying attention to peri-implant bone support, the existing prosthetic work, and whether any site would benefit from more localized imaging before further treatment.",
      "original_answer": "A restorative assessment and follow-up evaluation of the implants are suggested."
    },
    {
      "sample_index": 24,
      "id": "25_oral_ct_detection_02206_15465-B-06__qa_02",
      "source_record_id": "25_oral_ct_detection_02206_15465-B-06",
      "source_dataset": "25",
      "condition_category": "implant_other",
      "redrafted": true,
      "image": "assets/images/sample_024.jpg",
      "question": "What follow-up evaluation is suggested based on the presence of multiple implants?",
      "answer": "Based on the presence of multiple implants, follow-up evaluation should include comparing bone support across the implant sites, checking implant angulation and restorative alignment, and confirming that no area shows concerning radiographic change.",
      "original_answer": "A follow-up evaluation for restorative assessment is suggested based on the presence of multiple implants."
    },
    {
      "sample_index": 25,
      "id": "25_oral_ct_detection_02236_15484-B-02__qa_02",
      "source_record_id": "25_oral_ct_detection_02236_15484-B-02",
      "source_dataset": "25",
      "condition_category": "implant_other",
      "redrafted": true,
      "image": "assets/images/sample_025.jpg",
      "question": "What next-step treatment consideration is suggested by the visible implants?",
      "answer": "The next step would be a structured implant review with clinical correlation, focusing on marginal bone around the visible implants, prosthetic function, and whether dedicated periapical or sectional imaging is needed for any questionable site.",
      "original_answer": "A restorative assessment is suggested to evaluate the integration and function of the visible implants."
    },
    {
      "sample_index": 26,
      "id": "28_opg_detection_00170_165_jpg.rf.755e3b37c5773b66f694d96ddbf98662__qa_05",
      "source_record_id": "28_opg_detection_00170_165_jpg.rf.755e3b37c5773b66f694d96ddbf98662",
      "source_dataset": "28",
      "condition_category": "impacted_teeth",
      "redrafted": true,
      "image": "assets/images/sample_026.jpg",
      "question": "What is the recommended course of action for the visible Impacted teeth?",
      "answer": "For the visible impacted teeth, a more specific review should assess the mesioangular lower third-molar impaction, its contact with the adjacent second molar, and its relationship to the canal before deciding on surveillance versus extraction.",
      "original_answer": "A follow-up and further dental review are recommended for the impacted tooth."
    },
    {
      "sample_index": 27,
      "id": "25_oral_ct_detection_02251_15500-B-01__qa_02",
      "source_record_id": "25_oral_ct_detection_02251_15500-B-01",
      "source_dataset": "25",
      "condition_category": "single_implant",
      "redrafted": true,
      "image": "assets/images/sample_027.jpg",
      "question": "What is the next step for evaluating the single implant visible in the image?",
      "answer": "The next step for the visible single implant is a focused implant assessment, confirming surrounding bone support, implant position relative to adjacent structures, and readiness for restorative loading if clinically relevant.",
      "original_answer": "A follow-up evaluation of the implant is recommended."
    },
    {
      "sample_index": 28,
      "id": "28_opg_detection_00291_225_jpg.rf.e803650fe6ea719302d03e81e1cefeb4__qa_05",
      "source_record_id": "28_opg_detection_00291_225_jpg.rf.e803650fe6ea719302d03e81e1cefeb4",
      "source_dataset": "28",
      "condition_category": "caries",
      "redrafted": false,
      "image": "assets/images/sample_028.jpg",
      "question": "What is recommended for the visible Caries?",
      "answer": "A restorative assessment is recommended for the visible caries in the lower left area.",
      "original_answer": "A restorative assessment is recommended for the visible caries in the lower left area."
    },
    {
      "sample_index": 29,
      "id": "28_opg_detection_00035_113_jpg.rf.727e3f82de5bb8bb8ac47e91d094b2fe__qa_05",
      "source_record_id": "28_opg_detection_00035_113_jpg.rf.727e3f82de5bb8bb8ac47e91d094b2fe",
      "source_dataset": "28",
      "condition_category": "caries",
      "redrafted": false,
      "image": "assets/images/sample_029.jpg",
      "question": "What is recommended for the visible Caries?",
      "answer": "A restorative assessment is recommended for the visible caries.",
      "original_answer": "A restorative assessment is recommended for the visible caries."
    },
    {
      "sample_index": 30,
      "id": "28_opg_detection_00114_142_jpg.rf.e58718556ec924f3769333c8eb9f0559__qa_03",
      "source_record_id": "28_opg_detection_00114_142_jpg.rf.e58718556ec924f3769333c8eb9f0559",
      "source_dataset": "28",
      "condition_category": "caries",
      "redrafted": false,
      "image": "assets/images/sample_030.jpg",
      "question": "What is recommended for the visible caries finding?",
      "answer": "A restorative assessment is recommended for the visible caries finding.",
      "original_answer": "A restorative assessment is recommended for the visible caries finding."
    },
    {
      "sample_index": 31,
      "id": "28_opg_detection_00562_141_jpg.rf.a7d2f07e8fbc3051dd3f306d89babea4__qa_05",
      "source_record_id": "28_opg_detection_00562_141_jpg.rf.a7d2f07e8fbc3051dd3f306d89babea4",
      "source_dataset": "28",
      "condition_category": "caries",
      "redrafted": false,
      "image": "assets/images/sample_031.jpg",
      "question": "What is recommended for the visible Caries?",
      "answer": "A restorative assessment is recommended for the visible caries.",
      "original_answer": "A restorative assessment is recommended for the visible caries."
    },
    {
      "sample_index": 32,
      "id": "28_opg_detection_00441_48_jpg.rf.d240d1346868b3f60cb1339ab1cee72e__qa_04",
      "source_record_id": "28_opg_detection_00441_48_jpg.rf.d240d1346868b3f60cb1339ab1cee72e",
      "source_dataset": "28",
      "condition_category": "caries",
      "redrafted": false,
      "image": "assets/images/sample_032.jpg",
      "question": "What is recommended for the visible Caries?",
      "answer": "A restorative assessment is recommended for the visible caries.",
      "original_answer": "A restorative assessment is recommended for the visible caries."
    },
    {
      "sample_index": 33,
      "id": "25_oral_ct_detection_02182_15450-B-04__qa_02",
      "source_record_id": "25_oral_ct_detection_02182_15450-B-04",
      "source_dataset": "25",
      "condition_category": "implant_other",
      "redrafted": true,
      "image": "assets/images/sample_033.jpg",
      "question": "What conservative follow-up is suggested based on the visible implant findings?",
      "answer": "A conservative follow-up is reasonable, with review of peri-implant crestal bone, the stability of the implant-supported prostheses, and comparison with prior radiographs for any progressive change.",
      "original_answer": "A conservative follow-up with a restorative assessment is suggested for the visible implants."
    },
    {
      "sample_index": 34,
      "id": "28_opg_detection_00485_67_jpg.rf.ce02f1bda2249cebb471ff7801d0ad93__qa_05",
      "source_record_id": "28_opg_detection_00485_67_jpg.rf.ce02f1bda2249cebb471ff7801d0ad93",
      "source_dataset": "28",
      "condition_category": "caries",
      "redrafted": false,
      "image": "assets/images/sample_034.jpg",
      "question": "What is recommended for the visible Caries?",
      "answer": "A restorative assessment is recommended for the visible caries in the lower left area.",
      "original_answer": "A restorative assessment is recommended for the visible caries in the lower left area."
    },
    {
      "sample_index": 35,
      "id": "25_oral_ct_detection_02251_15500-B-01__qa_03",
      "source_record_id": "25_oral_ct_detection_02251_15500-B-01",
      "source_dataset": "25",
      "condition_category": "single_implant",
      "redrafted": true,
      "image": "assets/images/sample_035.jpg",
      "question": "What follow-up or treatment review is suggested by the visible single implants?",
      "answer": "A follow-up review of the visible single implant is suggested, emphasizing peri-implant bone levels, soft-tissue or clinical status, and whether the current position and restoration plan remain satisfactory.",
      "original_answer": "A follow-up evaluation of the single implant is suggested to assess its integration and surrounding bone health."
    },
    {
      "sample_index": 36,
      "id": "25_oral_ct_detection_02267_15507-B-02__qa_03",
      "source_record_id": "25_oral_ct_detection_02267_15507-B-02",
      "source_dataset": "25",
      "condition_category": "double_implants",
      "redrafted": true,
      "image": "assets/images/sample_036.jpg",
      "question": "What follow-up or treatment review is suggested by the visible double implants?",
      "answer": "A follow-up evaluation of the visible double implants should include checking osseous support at both implant sites, their relative alignment, and whether additional localized imaging is needed before or after prosthetic loading.",
      "original_answer": "A follow-up evaluation of the double implants is suggested to assess their stability and integration."
    },
    {
      "sample_index": 37,
      "id": "28_opg_detection_00145_155_jpg.rf.39c96a90732cf4a87d5151d714c5a441__qa_04",
      "source_record_id": "28_opg_detection_00145_155_jpg.rf.39c96a90732cf4a87d5151d714c5a441",
      "source_dataset": "28",
      "condition_category": "caries",
      "redrafted": false,
      "image": "assets/images/sample_037.jpg",
      "question": "What is recommended for the visible Caries?",
      "answer": "A restorative assessment is recommended for the visible caries.",
      "original_answer": "A restorative assessment is recommended for the visible caries."
    },
    {
      "sample_index": 38,
      "id": "25_oral_ct_detection_02172_15445-B-01__qa_03",
      "source_record_id": "25_oral_ct_detection_02172_15445-B-01",
      "source_dataset": "25",
      "condition_category": "single_implant",
      "redrafted": true,
      "image": "assets/images/sample_038.jpg",
      "question": "What follow-up or treatment review is suggested by the visible single implants?",
      "answer": "A treatment review of the visible implant site is suggested, focusing on marginal bone support, the condition of the implant-supported restoration, and clinical correlation for function and hygiene access.",
      "original_answer": "A restorative assessment of the single implants is suggested."
    },
    {
      "sample_index": 39,
      "id": "28_opg_detection_00501_72_jpg.rf.d3174348b9df7a9c9cc309b71fc94d31__qa_05",
      "source_record_id": "28_opg_detection_00501_72_jpg.rf.d3174348b9df7a9c9cc309b71fc94d31",
      "source_dataset": "28",
      "condition_category": "caries",
      "redrafted": false,
      "image": "assets/images/sample_039.jpg",
      "question": "What is recommended for the visible Caries?",
      "answer": "A restorative assessment is recommended for the visible caries.",
      "original_answer": "A restorative assessment is recommended for the visible caries."
    },
    {
      "sample_index": 40,
      "id": "25_oral_ct_detection_02190_15458-B-01__qa_03",
      "source_record_id": "25_oral_ct_detection_02190_15458-B-01",
      "source_dataset": "25",
      "condition_category": "single_implant",
      "redrafted": true,
      "image": "assets/images/sample_040.jpg",
      "question": "What follow-up or treatment review is suggested by the visible single implants?",
      "answer": "A follow-up review is suggested for the visible implant-supported region, with attention to peri-implant bone levels, prosthetic fit, and whether any site shows radiographic change that would justify closer interval imaging.",
      "original_answer": "A follow-up evaluation of the single implant is suggested to assess integration and surrounding tissue health."
    },
    {
      "sample_index": 41,
      "id": "28_opg_detection_00139_153_jpg.rf.1fb9e4fefa308bad9a814048998b3dea__qa_03",
      "source_record_id": "28_opg_detection_00139_153_jpg.rf.1fb9e4fefa308bad9a814048998b3dea",
      "source_dataset": "28",
      "condition_category": "impacted_teeth",
      "redrafted": true,
      "image": "assets/images/sample_041.jpg",
      "question": "What is recommended for the visible impacted teeth in the radiograph?",
      "answer": "Because multiple impacted teeth are visible in the radiograph, follow-up should include assessment of eruption path, effect on adjacent roots, and location relative to key structures before deciding on orthodontic or oral surgery management.",
      "original_answer": "A follow-up and further dental review are recommended for the impacted teeth."
    },
    {
      "sample_index": 42,
      "id": "28_opg_detection_00396_30_jpg.rf.97d16cb7ecc5a60094fdb5dcfcee7776__qa_03",
      "source_record_id": "28_opg_detection_00396_30_jpg.rf.97d16cb7ecc5a60094fdb5dcfcee7776",
      "source_dataset": "28",
      "condition_category": "impacted_teeth",
      "redrafted": true,
      "image": "assets/images/sample_042.jpg",
      "question": "What is recommended for the visible impacted teeth in the lower right region?",
      "answer": "For the impacted teeth in the lower right region, review should focus on the lower third-molar position, distal effect on the second molar, and neurovascular proximity, with oral surgery input if symptoms or pathology are present.",
      "original_answer": "A follow-up and further dental review are recommended for the impacted teeth in the lower right region."
    },
    {
      "sample_index": 43,
      "id": "25_oral_ct_detection_02161_15438-B-02__qa_02",
      "source_record_id": "25_oral_ct_detection_02161_15438-B-02",
      "source_dataset": "25",
      "condition_category": "single_implant",
      "redrafted": true,
      "image": "assets/images/sample_043.jpg",
      "question": "What follow-up or treatment review is suggested by the visible single implants?",
      "answer": "A follow-up review of the visible single implant is suggested, checking surrounding bone support, the implant-abutment relationship, and whether a focused periapical or sectional study is needed before final restorative decisions.",
      "original_answer": "A follow-up restorative assessment is suggested for the single implant located in the upper center."
    },
    {
      "sample_index": 44,
      "id": "28_opg_detection_00182_171_jpg.rf.7d7984cb5d77ba7a0a55c2ea41fa869d__qa_05",
      "source_record_id": "28_opg_detection_00182_171_jpg.rf.7d7984cb5d77ba7a0a55c2ea41fa869d",
      "source_dataset": "28",
      "condition_category": "caries",
      "redrafted": false,
      "image": "assets/images/sample_044.jpg",
      "question": "What is recommended for the visible Caries?",
      "answer": "A restorative assessment is recommended for the visible caries.",
      "original_answer": "A restorative assessment is recommended for the visible caries."
    },
    {
      "sample_index": 45,
      "id": "25_oral_ct_detection_02150_15429-B-01__qa_02",
      "source_record_id": "25_oral_ct_detection_02150_15429-B-01",
      "source_dataset": "25",
      "condition_category": "implant_other",
      "redrafted": true,
      "image": "assets/images/sample_045.jpg",
      "question": "What conservative follow-up is suggested based on the visible implant findings?",
      "answer": "A conservative follow-up is reasonable for the visible implant findings, with interval review of peri-implant bone, assessment of prosthetic status, and clinical correlation if there is discomfort, loading concern, or hygiene difficulty.",
      "original_answer": "A conservative follow-up with a restorative assessment is suggested based on the visible implant findings."
    },
    {
      "sample_index": 46,
      "id": "28_opg_detection_00184_172_jpg.rf.d17cda7483c641f9ef35747bf8178d0e__qa_05",
      "source_record_id": "28_opg_detection_00184_172_jpg.rf.d17cda7483c641f9ef35747bf8178d0e",
      "source_dataset": "28",
      "condition_category": "impacted_teeth",
      "redrafted": true,
      "image": "assets/images/sample_046.jpg",
      "question": "What is the recommended course of action for the visible Impacted teeth?",
      "answer": "The course of action for the visible impacted teeth should include review of angulation and space availability, plus assessment of contact with adjacent molars, so the team can decide between observation and referral for surgical removal.",
      "original_answer": "A follow-up and further dental review are recommended for the impacted teeth."
    },
    {
      "sample_index": 47,
      "id": "28_opg_detection_00305_232_jpg.rf.6f118762b9e6669db3b9417ac9e8f50b__qa_05",
      "source_record_id": "28_opg_detection_00305_232_jpg.rf.6f118762b9e6669db3b9417ac9e8f50b",
      "source_dataset": "28",
      "condition_category": "caries",
      "redrafted": false,
      "image": "assets/images/sample_047.jpg",
      "question": "What is recommended for the visible Caries?",
      "answer": "A restorative assessment is recommended for the visible caries.",
      "original_answer": "A restorative assessment is recommended for the visible caries."
    },
    {
      "sample_index": 48,
      "id": "28_opg_detection_00083_131_jpg.rf.598610406c5fa4e89aaf0647a7164a1c__qa_04",
      "source_record_id": "28_opg_detection_00083_131_jpg.rf.598610406c5fa4e89aaf0647a7164a1c",
      "source_dataset": "28",
      "condition_category": "caries",
      "redrafted": false,
      "image": "assets/images/sample_048.jpg",
      "question": "What is recommended for the visible Caries?",
      "answer": "A restorative assessment is recommended for the visible caries.",
      "original_answer": "A restorative assessment is recommended for the visible caries."
    },
    {
      "sample_index": 49,
      "id": "28_opg_detection_00459_58_jpg.rf.d3de1c86b93174247f712e8ade1236d3__qa_03",
      "source_record_id": "28_opg_detection_00459_58_jpg.rf.d3de1c86b93174247f712e8ade1236d3",
      "source_dataset": "28",
      "condition_category": "impacted_teeth",
      "redrafted": true,
      "image": "assets/images/sample_049.jpg",
      "question": "What is recommended for the visible impacted teeth in the lower right and lower left regions?",
      "answer": "For the impacted teeth in the lower right and lower left regions, a targeted review is suggested to assess the bilateral third-molar impaction pattern, adjacent second-molar involvement, and anatomic proximity before planning monitoring or extraction.",
      "original_answer": "A follow-up and further dental review are recommended for the impacted teeth in the lower right and lower left regions."
    },
    {
      "sample_index": 50,
      "id": "25_oral_ct_detection_02166_15441-B-02__qa_02",
      "source_record_id": "25_oral_ct_detection_02166_15441-B-02",
      "source_dataset": "25",
      "condition_category": "other",
      "redrafted": true,
      "image": "assets/images/sample_050.jpg",
      "question": "What next-step treatment consideration is suggested by the visible findings?",
      "answer": "A reasonable next step is a focused review of the posterior implant-supported restoration and surrounding bone, with clinical correlation for function or occlusion and additional localized imaging if any implant site appears questionable.",
      "original_answer": "A restorative assessment is suggested to evaluate the double implants and surrounding structures."
    }
  ]
};
